// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';

// GitHub Pages project hosting: the site is served from a subdirectory, so
// `site` is the origin and `base` is the repository name. Both are needed —
// `base` alone leaves canonical URLs and the sitemap pointing at the root.
export default defineConfig({
	site: 'https://benjaminabbitt.github.io',
	base: '/hew',
	integrations: [
		mermaid(), // Must come BEFORE starlight for diagram rendering
		starlight({
			title: 'hew',
			description:
				'A structure-aware replacement for patch(1) and diff(1) for JSON, JSONC, YAML, TOML and HCL.',
			social: {
				github: 'https://github.com/benjaminabbitt/hew',
			},
			editLink: {
				baseUrl: 'https://github.com/benjaminabbitt/hew/edit/main/website/',
			},
			lastUpdated: true,
			sidebar: [
				{
					label: 'Introduction',
					link: '/',
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Writing a .hew patch', link: '/guides/writing-a-patch/' },
						{ label: 'The exit-code contract', link: '/guides/exit-codes/' },
					],
				},
				{
					label: 'Architecture',
					link: '/architecture/',
				},
				{
					// Generated by `just examples` from examples/ by actually running
					// the CLI (see .github/workflows/pages.yml) — never checked in, so
					// this MUST autogenerate rather than enumerate pages, or a fresh
					// clone with no transcripts generated yet fails the build on a
					// dead link.
					label: 'Examples',
					autogenerate: { directory: 'examples' },
				},
				{
					label: 'The standard',
					link: '/standard/',
				},
			],
		}),
	],
});
