package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// scenario is one executable example: the prose that frames it, the fixture
// files that ship with it, and the ordered steps whose real output becomes the
// transcript. The fixtures live beside scenario.yaml in the same directory —
// the scenario directory IS the scratch copy's starting state.
type scenario struct {
	// Dir is the scenario directory; Name its base name, which becomes the
	// generated page's slug.
	Dir  string `yaml:"-"`
	Name string `yaml:"-"`

	Title       string `yaml:"title"`
	Description string `yaml:"description"`
	// Order fixes the sidebar position. Starlight sorts an autogenerated
	// group by frontmatter order, so a scenario that reads as "lesson two"
	// says so here rather than depending on its name sorting that way.
	Order int `yaml:"order"`
	// Intro is the one-paragraph framing rendered under the title.
	Intro string `yaml:"intro"`
	// Show lists the starting fixtures to display before the first step, in
	// the order given — an explicit list rather than a directory scan,
	// because a scenario's fixtures are not equally interesting and a scan
	// would order them by accident.
	Show  []string `yaml:"show"`
	Steps []step   `yaml:"steps"`
	// Outro is optional closing prose.
	Outro string `yaml:"outro"`
}

// step is one command in the transcript, plus the file writes that set it up
// and the files whose result it is worth showing afterwards.
type step struct {
	Title string `yaml:"title"`
	Note  string `yaml:"note"`
	// Write holds pre-run file writes: the edits a human would make between
	// commands, made explicit so the transcript can show them.
	Write []write `yaml:"write"`
	// Git holds argv lists for git, without argv0, run before Run and
	// rendered as part of the same console block. It exists for the one
	// scenario that needs a repository (the REV:path anchor form of `hew
	// diff`); the generator runs git with a pinned identity and clock so the
	// transcript stays byte-stable. Every git command must succeed — a
	// scenario's repository is scaffolding, not the subject.
	Git [][]string `yaml:"git"`
	// Run is argv for the hew binary, without argv0 ("apply", "-i", …). This
	// is the step's subject, and the exit code the page reports.
	Run []string `yaml:"run"`
	// ExpectExit is the exit code the scenario asserts of Run. The generator
	// fails if the real run disagrees, so a transcript can never quietly
	// document behavior the CLI no longer has.
	ExpectExit int `yaml:"expect_exit"`
	// Watch names files whose before/after pair is shown after the step: the
	// resulting file plus a conventional unified diff for legibility.
	Watch []string `yaml:"watch"`
	// Show names files to display in full after the step, with no diff — for
	// artifacts a step creates from nothing (a recorded run, an emitted
	// patch).
	Show []string `yaml:"show"`
	// Unchanged names files asserted byte-identical across the step. The
	// assertion is the point of the stale-refusal scenario, so it is checked,
	// not narrated.
	Unchanged []string `yaml:"unchanged"`
	// Identical asserts two files in the scratch copy have identical bytes —
	// the claim the diff-then-apply round trip exists to make. Written as
	// "a == b"; the generator fails if it is false and the page states it.
	Identical []string `yaml:"identical"`
	// Caption is prose rendered after the command's output.
	Caption string `yaml:"caption"`
}

// write is one pre-run file write.
type write struct {
	Path    string `yaml:"path"`
	Content string `yaml:"content"`
	// Hide suppresses displaying the written file, for setup that is noise.
	Hide bool `yaml:"hide"`
	// Label overrides the heading shown above the written file.
	Label string `yaml:"label"`
}

// loadScenarios reads every scenario directory under dir, sorted by Order then
// Name so the generated pages and the index are stable regardless of the
// filesystem's directory order.
func loadScenarios(dir string) ([]*scenario, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []*scenario
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		sc, err := loadScenario(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, err
		}
		out = append(out, sc)
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Order != out[j].Order {
			return out[i].Order < out[j].Order
		}
		return out[i].Name < out[j].Name
	})
	return out, nil
}

func loadScenario(dir string) (*scenario, error) {
	manifest := filepath.Join(dir, "scenario.yaml")
	src, err := os.ReadFile(manifest)
	if err != nil {
		return nil, err
	}
	sc := &scenario{Dir: dir, Name: filepath.Base(dir)}
	dec := yaml.NewDecoder(strings.NewReader(string(src)))
	dec.KnownFields(true)
	if err := dec.Decode(sc); err != nil {
		return nil, fmt.Errorf("%s: %w", manifest, err)
	}
	if err := sc.validate(); err != nil {
		return nil, fmt.Errorf("%s: %w", manifest, err)
	}
	return sc, nil
}

func (sc *scenario) validate() error {
	if sc.Title == "" {
		return fmt.Errorf("title is required")
	}
	if sc.Description == "" {
		return fmt.Errorf("description is required (Starlight frontmatter)")
	}
	if len(sc.Steps) == 0 {
		return fmt.Errorf("at least one step is required")
	}
	for i, st := range sc.Steps {
		if len(st.Run) == 0 && len(st.Git) == 0 && len(st.Write) == 0 {
			return fmt.Errorf("step %d: needs one of run, git or write", i+1)
		}
		for _, pair := range st.Identical {
			if len(strings.Split(pair, " == ")) != 2 {
				return fmt.Errorf("step %d: identical entry %q must read \"a == b\"", i+1, pair)
			}
		}
	}
	return nil
}
